# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Precon API
  description: Move your app forward with the Precon API
  version: "1.0.0"
# the domain of the service
host: api.precon.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
securityDefinitions:
  API Key:
    type: apiKey
    in: header
    name: key
paths:
  /library/content:
    post:
      summary: Content
      description:  The endpoint is you for adding content to your library
      parameters:
        - name: title
          in: body
          description: Title of the content.
          required: true
          schema:
            type: string
          
        - name: type
          in: body
          description: Type of the content - movie, video, tvshow, tvseries.
          required: true
          schema:
            type: string
          
        - name: classification
          in: body
          description: Comma seperated list of tags or genere or classification of the content. Like musicvideo, rap, punjabi Or sports, cricket, highlights or biopic, sports 
          required: true
          schema:
            type: string
          
        - name: language
          in: body
          description: Language of the content
          required: false
          schema:
            type: string
          
        - name: runningTime
          in: body
          description: Playback time of the content in seconds
          required: false
          schema:
            type: integer
            format: int32
          
        - name: cast
          in: body
          description: Array of cast starring in the content
          required: false
          schema:
            type: array
            items:
              type: string
          
        - name: directors
          in: body
          description: Array of directors
          required: false
          schema:
            type: array
            items:
              type: string
          
        - name: studios
          in: body
          description: Array of studios or production houses this content belongs to - Viacom, Disney, AIB, indie
          required: false
          schema:
            type: array
            items:
              type: string
          
        - name: releasedOn
          in: body
          description: Date on which the content was released.
          required: false
          schema:
            type: string
            format: date
          
        - name: synopsis
          in: body
          description: Synopsis.
          required: false
          schema:
            type: string
          
      tags:
        - Content
      responses:
        200:
          description: Content successfully created in your library
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /integrator:
    post:
      summary: Integrator details
      description: The endpoint is use for adding integrator
      parameters:
        - name: name
          in: body
          description: Friendly name of the integrator
          required: true
          schema:
            type: string
      tags:
        - Integrator
      responses:
        200:
          description: Integrator created
          schema:
            $ref: '#/definitions/IntegratorRegistration' 
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'    
definitions:
  IntegratorRegistration:
    type: object
    properties:
      id:
        type: string
        format: string
      apiKey:
        type: string
        format: string
  Content:
    type: object
    properties:
      title:
        type: string
        format: string
      type:
        type: string
        format: string
      classification:
        type: string
        format: string
      language:
        type: string
        format: string
      runningTime:
        type: integer
        format: int32
      cast:
        type: array
        items:
          type: string
      directors:
        type: array
        items:
          type: string
      studios:
        type: array
        items:
          type: string
      releasedOn:
        type: string
        format: date
      synopsis:
        type: string
        format: string
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string