# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Precon API
  description: Move your app forward with the Precon API
  version: "1.0.0"
# the domain of the service
host: api.precon.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
securityDefinitions:
  API Key:
    type: apiKey
    in: header
    name: key
paths:
  /library/content:
    post:
      summary: Content
      description:  The endpoint is you for adding content to your library
      parameters:
        - name: content 
          in: body
          description: Content Object
          required: true
          schema:
            $ref: '#/definitions/Content'
          
      tags:
        - Content
      responses:
        200:
          description: Content successfully created in your library
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /integrator:
    post:
      summary: Integrator details
      description: The endpoint is use for adding integrator
      parameters:
        - name: name
          in: body
          description: Friendly name of the integrator
          required: true
          schema:
            type: string
      tags:
        - Integrator
      responses:
        200:
          description: Integrator created
          schema:
            $ref: '#/definitions/IntegratorRegistration' 
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'    
definitions:
  IntegratorRegistration:
    type: object
    properties:
      id:
        type: string
        format: string
      apiKey:
        type: string
        format: string
        
  Content:
    type: object
    properties:
      title:
        type: string
        format: string
      type:
        type: string
        format: string
      classification:
        type: string
        format: string
      language:
        type: string
        format: string
      runningTime:
        type: integer
        format: int32
      cast:
        type: array
        items:
          type: string
      directors:
        type: array
        items:
          type: string
      studios:
        type: array
        items:
          type: string
      releasedOn:
        type: string
        format: date
      synopsis:
        type: string
        format: string
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string