# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Precon API
  description: Add advance personalization and recommendation engine to your app
  version: "1.0.0"
# the domain of the service
host: api.precon.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
produces:
  - application/json
security:
  - x-apiKey: []
paths:
  /content:
    post:
      summary: Add Content
      description: Use this endpoint to add content
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: content 
          in: body
          description: Content Object
          required: true
          schema:
            $ref: '#/definitions/Content'
      tags:
        - Content
      responses:
        200:
          description: Content successfully added
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /content/bulk:
    post:
      summary: Add Content in bulk
      description: Use this endpoint to bulk upload your content library
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: content 
          in: body
          description: json containing the entire content library
          required: true
          schema:
            $ref: '#/definitions/BulkContent'
      tags:
        - Content
      responses:
        200:
          description: Content successfully added 
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'           
            
  /integration:
    post:
      summary: Add integration
      description: The endpoint is used for adding integrations
      parameters:
        - name: name
          in: body
          description: Friendly name for the integration
          required: true
          schema:
            type: string
      tags:
        - Integration
      responses:
        200:
          description: Integration added
          schema:
            $ref: '#/definitions/IntegrationRegistration' 
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'    
  
  /user:
    post:
      summary: Add user 
      description: The endpoint is used for adding users
      parameters:
        - name: user 
          in: body
          description: User Object
          required: true
          schema:
            $ref: '#/definitions/User'
      tags:
        - User      
      responses:
        200:
          description: User successfully added
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /interest:
    post:
      summary: Capture user interests 
      description: The endpoint is used for user interest
      parameters:
        - name: interests 
          in: body
          description: User interest Object
          required: true
          schema:
            $ref: '#/definitions/Interest'
      tags:
        - User      
      responses:
        200:
          description: User interests successfully added
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    
securityDefinitions:
  x-apiKey:
    type: apiKey
    in: header
    name: x-apiKey
    description: api key of the integration
definitions:
  IntegrationRegistration:
    type: object
    properties:
      id:
        type: string
        format: string
      apiKey:
        type: string
        format: string
        
  Content:
    type: object
    required:
      - title
      - type
      - classification
      - sourceId
    properties:
      title:
        description: Title of the content.
        type: string
        format: string
      type:
        description: Type of the content - movie, video, tvshow, tvseries.
        type: string
        format: string
      classification:
        description: Comma seperated list of tags or genere or classification of the content. Like music, video, rap, punjabi Or sports, cricket, highlights or biopic, sports 
        type: string
        format: string
      sourceId:
        description: Unique id of the content as per the integration system.
        type: string
        format: string  
      integrationId:
        description: Unique id of the integrator as per the integration system.
        type: string
        format: string
      language:
        description: Language of the content.
        type: string
        format: string
      runningTimeInSecs:
        description: Playback time of the content in seconds.
        type: integer
        format: int32
      cast:
        description: Comma separated list of cast starring in the content.
        type: string
        format: string
      directors:
        description: Comma separated list of directors.
        type: string
        format: string
      studios:
        description: Comma separated list of studios.
        type: string
        format: string
      releasedOn:
        description: Date on which the content was released.
        type: string
        format: date
      synopsis:
        description: Synopsis of the content.
        type: string
        format: string
      keywords:
        description: keywords related to content.
        type: string
        format: string
  
  BulkContent:
    type: object
    properties:
      content:
        type: object
        format: object
  
  User:
    type: object
    required:
      - email
    properties:
      email:
        description: email id of the user.
        type: string
        format: email
      
      phone:
        description: phone number of the user.
        type: integer
        format: int32
        
      gender:
        description: gender of the user.
        type: string
        format: string
      
      age:
        description: age of the user.
        type: integer
        format: int32  
      
      country:
        description: country of the user.
        type: string
        format: string
      
      sourceId:
        description: source id from the integrator
        type: string
        format: string
  
  Interest:
    type: object
    required:
      - email
      - contentSourceId
    properties:
      email:
        description: email id of the user.
        type: string
        format: email
      
      contentSourceId:
        description: source id of the content.
        type: string
        format: string
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string