# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Precon API
  description: Move your app forward with the Precon API
  version: "1.0.0"
# the domain of the service
host: api.precon.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json

paths:
  /library/content:
    post:
      summary: Content
      description:  The endpoint is you for adding content to your library.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: content 
          in: body
          description: Content Object
          required: true
          schema:
            $ref: '#/definitions/Content'
        - name: apiKey 
          in: header
          description: API key of the integrator.
          required: true
          type: string
          format: string
      tags:
        - Content
      responses:
        200:
          description: Content successfully created in your library
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /integration:
    post:
      summary: Integrator details
      description: The endpoint is use for adding integrator
      parameters:
        - name: name
          in: body
          description: Friendly name of the integrator
          required: true
          schema:
            type: string
      tags:
        - Integrator
      responses:
        200:
          description: Integrator created
          schema:
            $ref: '#/definitions/IntegratorRegistration' 
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'    
definitions:
  IntegratorRegistration:
    type: object
    properties:
      id:
        type: string
        format: string
      apiKey:
        type: string
        format: string
        
  Content:
    type: object
    required:
      - title
      - type
      - classification
    properties:
      title:
        description: Title of the content.
        type: string
        format: string
      type:
        description: Type of the content - movie, video, tvshow, tvseries.
        type: string
        format: string
      classification:
        description: Comma seperated list of tags or genere or classification of the content. Like music, video, rap, punjabi Or sports, cricket, highlights or biopic, sports 
        type: string
        format: string
      language:
        description: Language of the content.
        type: string
        format: string
      runningTime:
        description: Playback time of the content in seconds.
        type: integer
        format: int32
      cast:
        description: Comma separated list of cast starring in the content.
        type: string
        format: string
      directors:
        description: Comma separated list of directors.
        type: string
        format: string
      studios:
        description: Comma separated list of studios.
        type: string
        format: string
      releasedOn:
        description: Date on which the content was released.
        type: string
        format: date
      synopsis:
        description: Synopsis of the content.
        type: string
        format: string
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string